# Generated by Django 3.2.11 on 2023-08-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_validator', '0009_auto_20230823_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomValidationError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=255, null=True)),
                ('error_count', models.IntegerField(default=0)),
            ],
        ),
    ]
